# Generated by Django 4.1.5 on 2023-07-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0002_alter_oier_enroll_middle_alter_oier_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
