# Generated by Django 4.1.5 on 2023-07-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0003_alter_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='uid',
            field=models.IntegerField(default=0, verbose_name='OIer'),
        ),
    ]
