# Generated by Django 4.1.5 on 2023-07-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0004_alter_record_score_alter_record_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oier',
            name='CCF_level',
            field=models.IntegerField(max_length=5),
        ),
    ]
