# Generated by Django 4.1.5 on 2023-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggySQL', '0005_alter_oier_ccf_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oier',
            name='CCF_level',
            field=models.IntegerField(),
        ),
    ]
